name: Deploy application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # pm2 stop server
            # rm -r ~/final-project-backend
            # mkdir -p ~/final-project-backend/ 
            # cd ~/final-project-backend/
            # git clone https://github.com/tizenmile/final-project-backend.git .
            # npm install
            # pm2 start server.js # start as a background service.
            cd ~/final-project-backend/
            git pull
            npm install
            cp ~/.env ~/final-project-backend/
            pm2 restart server.js